import React from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { SessionDetail } from "./HistoryTable";

type Props = {
  sessionDetail: SessionDetail;
  trigger?: React.ReactNode;
};

// Define the structure of your report object
interface ReportData {
  summary: string;
  symptoms: string[];
  duration: string;
  severity: string;
  medicationsMentioned: string[];
  recommendations: string[];
}

export function ViewReportDialog({ sessionDetail, trigger }: Props) {
  const { report } = sessionDetail || {};

  // Helper to safe parse the report if it comes as a string or object
  let parsedReport: ReportData | null = null;
  if (report) {
    if (typeof report === "string") {
      try {
        parsedReport = JSON.parse(report);
      } catch (e) {
        console.error("Error parsing report JSON:", e);
      }
    } else {
      parsedReport = report as unknown as ReportData;
    }
  }

  return (
    <Dialog>
      <DialogTrigger asChild>
        {trigger || <Button variant="outline">View Report</Button>}
      </DialogTrigger>
      
      {/* Increased max-width to match the screenshot layout */}
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-center text-2xl font-bold">
            Medical AI Voice Agent Report
          </DialogTitle>
          <DialogDescription className="hidden">
            Consultation summary and details
          </DialogDescription>
        </DialogHeader>

        {parsedReport ? (
          <div className="flex flex-col gap-6 mt-4 text-gray-700">
            
            {/* Summary Text */}
            <div className="text-gray-600 leading-relaxed">
              {parsedReport.summary}
            </div>

            {/* Symptoms Section */}
            <div>
              <h3 className="text-blue-600 font-bold text-lg border-b-2 border-blue-600 pb-2 mb-3">
                Symptoms
              </h3>
              <ul className="list-disc pl-5 space-y-1">
                {parsedReport.symptoms?.map((item, index) => (
                  <li key={index} className="capitalize">{item}</li>
                ))}
              </ul>
            </div>

            {/* Duration & Severity Section */}
            <div>
              <h3 className="text-blue-600 font-bold text-lg border-b-2 border-blue-600 pb-2 mb-3">
                Duration & Severity
              </h3>
              <div className="flex flex-wrap gap-10">
                <p>
                  <span className="font-bold text-gray-800">Duration: </span>
                  {parsedReport.duration || "Not specified"}
                </p>
                <p>
                  <span className="font-bold text-gray-800">Severity: </span>
                  {parsedReport.severity || "Not specified"}
                </p>
              </div>
            </div>

            {/* Medications Section */}
            <div>
              <h3 className="text-blue-600 font-bold text-lg border-b-2 border-blue-600 pb-2 mb-3">
                Medications Mentioned
              </h3>
              <ul className="list-disc pl-5 space-y-1">
                {parsedReport.medicationsMentioned?.length > 0 ? (
                  parsedReport.medicationsMentioned.map((item, index) => (
                    <li key={index} className="capitalize">{item}</li>
                  ))
                ) : (
                  <li>None mentioned</li>
                )}
              </ul>
            </div>

            {/* Recommendations Section */}
            <div>
              <h3 className="text-blue-600 font-bold text-lg border-b-2 border-blue-600 pb-2 mb-3">
                Recommendations
              </h3>
              <ul className="list-disc pl-5 space-y-1">
                {parsedReport.recommendations?.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </div>

            {/* Footer Disclaimer */}
            <div className="border-t pt-4 mt-4">
              <p className="text-center text-xs text-gray-400">
                This report was generated by an AI Medical Assistant for informational purposes only.
              </p>
            </div>

          </div>
        ) : (
          <div className="text-center py-10 text-gray-500">
            No report available for this session.
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

export default ViewReportDialog;